<template>
    <div>

    </div>
</template>

<script setup>
const standard5stars = [
  { name: "Diluc", rarity: 5, image: "/public/diluc_wish.webp" },
  { name: "Jean", rarity: 5, image: "/public/jean_wish.webp" },
  { name: "Mona", rarity: 5, image: "/public/mona_wish.webp" },
  { name: "Qiqi", rarity: 5, image: "/public/qiqi_wish.webp" },
  { name: "Keqing", rarity: 5, image: "/public/keqing_wish.webp" },
  { name: "Tighnari", rarity: 5, image: "/public/tighnari_wish.webp" },
  { name: "Dehya", rarity: 5, image: "/public/dehya_wish.webp" },
  { name: "Yumemizuki Mizuki", rarity: 5, image: "/public/yumemizuki_mizuki_wish.webp" },
];
const limited5stars = [
  { name: "Venti", rarity: 5, image: "/public/venti_wish.webp" },
  { name: "Klee", rarity: 5, image: "/public/klee_wish.webp" },
  { name: "Zhongli", rarity: 5, image: "/public/zhongli_wish.webp" },
  { name: "Tartaglia", rarity: 5, image: "/public/Tartaglia_wish.webp" },
  { name: "Albedo", rarity: 5, image: "/public/albedo.webp" },
  { name: "Ganyu", rarity: 5, image: "/public/ganyu_wish.webp" },
  { name: "Xiao", rarity: 5, image: "/public/xiao_wish.webp" },
  { name: "Hu Tao", rarity: 5, image: "/public/hu_tao_wish.webp" },
  { name: "Eula", rarity: 5, image: "/public/eula_wish.webp" },
  { name: "Kaedehara Kazuha", rarity: 5, image: "/public/kaedehara_kazuha_wish.webp" },
  { name: "Kamisato Ayaka", rarity: 5, image: "/public/kamisato_ayaka_wish.webp" },
  { name: "Yoimiya", rarity: 5, image: "/public/yoimiya_wish.webp" },
  { name: "Raiden Shogun", rarity: 5, image: "/public/raiden_shogun_wish.webp" },
  { name: "Sangonomiya Kokomi", rarity: 5, image: "/public/sangonomiya_kokomi_wish.webp" },
  { name: "Arataki Itto", rarity: 5, image: "/public/itto.webp" },
  { name: "Shenhe", rarity: 5, image: "/public/shenhe_wish.webp" },
  { name: "Yae Miko", rarity: 5, image: "/public/yae_miko_wish.webp" },
  { name: "Kamisato Ayato", rarity: 5, image: "/public/kamisato_ayato_wish.webp" },
  { name: "Yelan", rarity: 5, image: "/public/yelan_wish.webp" },
  { name: "Cyno", rarity: 5, image: "/public/cyno.webp" },
  { name: "Nilou", rarity: 5, image: "/public/nilou_wish.webp" },
  { name: "Nahida", rarity: 5, image: "/public/nahida_wish.webp" },
  { name: "Wanderer", rarity: 5, image: "/public/wanderer_wish.webp" },
  { name: "Alhaitham", rarity: 5, image: "/public/alhaitham.webp" },
  { name: "Baizhu", rarity: 5, image: "/public/baizhu.webp" },
  { name: "Lyney", rarity: 5, image: "/public/lyney_wish.webp" },
  { name: "Neuvillette", rarity: 5, image: "/public/neuvillette_wish.webp" },
  { name: "Wriothesley", rarity: 5, image: "/public/wriothesley_wish.webp" },
  { name: "Furina", rarity: 5, image: "/public/furina_wish.webp" },
  { name: "Navia", rarity: 5, image: "/public/navia_wish.webp" },
  { name: "Xianyun", rarity: 5, image: "/public/xianyun_wish.webp" },
  { name: "Chiori", rarity: 5, image: "/public/chiori.webp" },
  { name: "Arlecchino", rarity: 5, image: "/public/arle.webp" },
  { name: "Clorinde", rarity: 5, image: "/public/clorinde.webp" },
  { name: "Sigewinne", rarity: 5, image: "/public/sigewinne_wish.webp" },
  { name: "Emilie", rarity: 5, image: "/public/emilie_wish.webp" },
  { name: "Mualani", rarity: 5, image: "/public/mualani_wish.webp" },
  { name: "Kinich", rarity: 5, image: "/public/kinich_wish.webp" },
  { name: "Xilonen", rarity: 5, image: "/public/xilonen_wish.webp" },
  { name: "Chasca", rarity: 5, image: "/public/chasca.webp" },
  { name: "Mauvika", rarity: 5, image: "/public/mauvika_wish.webp" },
  { name: "Citlali", rarity: 5, image: "/public/citlali.webp" },
  { name: "Varesa", rarity: 5, image: "/public/varesa_wish.webp" },
  { name: "Escoffier", rarity: 5, image: "/public/escoffier_wish.webp" },
  { name: "Skirk", rarity: 5, image: "/public/skirk_wish.webp" },
  { name: "Ineffa", rarity: 5, image: "/public/ineffa_wish.webp" },
  { name: "Lauma", rarity: 5, image: "/public/lauma_wish.webp" },
  { name: "Flins", rarity: 5, image: "/public/flins_wish.webp" },
  { name: "Nefer", rarity: 5, image: "/public/nefer_wish.webp" },
  { name: "Durin", rarity: 5, image: "/public/durin_wish.webp" },
  { name: "Columbina", rarity: 5, image: "/public/columbina.webp" },
  { name: "Zibai", rarity: 5, image: "/public/zibai_wish.webp" },
];
const fourStars = [
  { name: "Amber", rarity: 4, image: "/public/amber.webp" },
  { name: "Kaeya", rarity: 4, image: "/public/kaeya_wish.webp" },
  { name: "Lisa", rarity: 4, image: "/public/lisa_wish.webp" },
  { name: "Barbara", rarity: 4, image: "/public/barbara.webp" },
  { name: "Razor", rarity: 4, image: "/public/razor_wish.webp" },
  { name: "Xiangling", rarity: 4, image: "/public/xiangling_wish.webp" },
  { name: "Beidou", rarity: 4, image: "/public/beidou.webp" },
  { name: "Xingqiu", rarity: 4, image: "/public/xingqiu_wish.webp" },
  { name: "Ningguang", rarity: 4, image: "/public/ningguang_wish.webp" },
  { name: "Fischl", rarity: 4, image: "/public/fischl_wish.webp" },
  { name: "Bennett", rarity: 4, image: "/public/benny.webp" },
  { name: "Noelle", rarity: 4, image: "/public/noelle_wish.webp" },
  { name: "Chongyun", rarity: 4, image: "/public/chongyun.webp" },
  { name: "Sucrose", rarity: 4, image: "/public/sucrose_wish.webp" },
  { name: "Diona", rarity: 4, image: "/public/diona_wish.webp" },
  { name: "Xinyan", rarity: 4, image: "/public/xinyan_wish.webp" },
  { name: "Rosaria", rarity: 4, image: "/public/rosaria_wish.webp" },
  { name: "Yanfei", rarity: 4, image: "/public/yanfei_wish.webp" },
  { name: "Sayu", rarity: 4, image: "/public/sayu_wish.webp" },
  { name: "Kujou Sara", rarity: 4, image: "/public/kujou_sara_wish.webp" },
  { name: "Thoma", rarity: 4, image: "/public/thoma_wish.webp" },
  { name: "Gorou", rarity: 4, image: "/public/gorou_wish.webp" },
  { name: "Yun Jin", rarity: 4, image: "/public/yun_jin_wish.webp" },
  { name: "Kuki Shinobu", rarity: 4, image: "/public/kuki_shinobu_wish.webp" },
  { name: "Shikanoin Heizou", rarity: 4, image: "/public/shikanoin_heizou_wish.webp" },
  { name: "Collei", rarity: 4, image: "/public/collei.webp" },
  { name: "Dori", rarity: 4, image: "/public/dori_wish.webp" },
  { name: "Candace", rarity: 4, image: "/public/candace.webp" },
  { name: "Layla", rarity: 4, image: "/public/layla_wish.webp" },
  { name: "Faruzan", rarity: 4, image: "/public/faruzan_wish.webp" },
  { name: "Yaoyao", rarity: 4, image: "/public/yaoyao_wish.webp" },
  { name: "Mika", rarity: 4, image: "/public/mika_wish.webp" },
  { name: "Kaveh", rarity: 4, image: "/public/kaveh_wish.webp" },
  { name: "Kirara", rarity: 4, image: "/public/kirara_wish.webp" },
  { name: "Lynette", rarity: 4, image: "/public/lynette_wish.webp" },
  { name: "Freminet", rarity: 4, image: "/public/freminet_wish.webp" },
  { name: "Charlotte", rarity: 4, image: "/public/charlotte.webp" },
  { name: "Cheveruse", rarity: 4, image: "/public/cheveruse.webp" },
  { name: "Gaming", rarity: 4, image: "/public/gaming_wish.webp" },
  { name: "Sethos", rarity: 4, image: "/public/sethos_wish.webp" },
  { name: "Kachina", rarity: 4, image: "/public/kachina_wish.webp" },
  { name: "Ororon", rarity: 4, image: "/public/ororon_wish.webp" },
  { name: "Lan Yan", rarity: 4, image: "/public/lan_yan_wish.webp" },
  { name: "Iansan", rarity: 4, image: "/public/iansan_wish.webp" },
  { name: "Ifa", rarity: 4, image: "/public/ifa_wish.webp" },
  { name: "Dahlia", rarity: 4, image: "/public/dahlia_wish.webp" },
  { name: "Aino", rarity: 4, image: "/public/aino.webp" },
  { name: "Jahoda", rarity: 4, image: "/public/jahoda_wish.webp" },
  { name: "Favonius Sword", rarity: 4, image: "/public/weapon_favonius_sword.webp" },
  { name: "Favonius Lance", rarity: 4, image: "/public/weapon_favonius_lance.webp" },
  { name: "Favonius Warbow", rarity: 4, image: "/public/weapon_favonius_warbow.webp" },
  { name: "Favonius Codex", rarity: 4, image: "/public/weapon_favonius_codex.webp" },
  { name: "Favonius Greatsword", rarity: 4, image: "/public/weapon_favonius_greatsword.webp" },
  { name: "Sacrificial Sword", rarity: 4, image: "/public/weapon_sacrificial_sword.webp" },
  { name: "Sacrificial Bow", rarity: 4, image: "/public/weapon_sacrificial_bow.webp" },
  { name: "Sacrificial Fragments", rarity: 4, image: "/public/weapon_sacrificial_fragments.webp" },
  { name: "Sacrificial Greatsword", rarity: 4, image: "/public/weapon_sacrificial_greatsword.webp" },
  { name: "The Widsith", rarity: 4, image: "/public/weapon_the_widsith.webp" },
  { name: "Rust", rarity: 4, image: "/public/weapon_rust.webp" },
  { name: "Dragon's Bane", rarity: 4, image: "/public/weapon_dragon's_bane.webp" },
  { name: "Lion's Roar", rarity: 4, image: "/public/weapon_lion's_roar.webp" },
  { name: "Eye of Perception", rarity: 4, image: "/public/weapon_eye_of_perception.webp" },
  { name: "The Flute", rarity: 4, image: "/public/weapon_the_flute.webp" }
];
const threeStarWeapons = [
  { name: "Amber Catalyst", rarity: 3, image: "/public/weapon_amber_catalyst.webp" },
  { name: "Black Tassel", rarity: 3, image: "/public/weapon_black_tassel.webp" },
  { name: "Bloodtainted Greatsword", rarity: 3, image: "/public/weapon_bloodtainted_greatsword.webp" },
  { name: "Cool Steel", rarity: 3, image: "/public/weapon_cool_steel.webp" },
  { name: "Dark Iron Sword", rarity: 3, image: "/public/weapon_dark_iron_sword.webp" },
  { name: "Debate Club", rarity: 3, image: "/public/weapon_debate_club.webp" },
  { name: "Emerald Orb", rarity: 3, image: "/public/weapon_emerald_orb.webp" },
  { name: "Ferrous Shadow", rarity: 3, image: "/public/weapon_ferrous_shadow.webp" },
  { name: "Fillet Blade", rarity: 3, image: "/public/weapon_fillet_blade.webp" },
  { name: "Halberd", rarity: 3, image: "/public/weapon_halberd.webp" },
  { name: "Harbinger of Dawn", rarity: 3, image: "/public/weapon_harbinger_of_dawn.webp" },
  { name: "Magic Guide", rarity: 3, image: "/public/weapon_magic_guide.webp" },
  { name: "Otherworldly Story", rarity: 3, image: "/public/weapon_otherworldly_story.webp" },
  { name: "Raven Bow", rarity: 3, image: "/public/weapon_raven_bow.webp" },
  { name: "Sharpshooter's Oath", rarity: 3, image: "/public/weapon_sharpshooter's_oath.webp" },
  { name: "Skyrider Sword", rarity: 3, image: "/public/weapon_skyrider_sword.webp" },
  { name: "Slingshot", rarity: 3, image: "/public/weapon_slingshot.webp" },
  { name: "Thrilling Tales of Dragon Slayers", rarity: 3, image: "/public/weapon_thrilling_tales_of_dragon_slayers.webp" },
  { name: "Traveler's Handy Sword", rarity: 3, image: "/public/weapon_traveler's_handy_sword.webp" },
  { name: "Twin Nephrite", rarity: 3, image: "/public/weapon_twin_nephrite.webp" },
];

</script>

<style scoped>

</style>